# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Mary Acuna
description: "Hello my name is Mary, and I'm studying Data Science.  My portfolio focuses on interesting projects I've been working on, with a strong emphasis on business impact. Please visit my Github & LinkedIn pages by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Wisconsin, US"
resume_url: /docs/resumetbd.docx
avatar_image: /img/measq.JPG

#-------------------------------
# Contact links
linkedln: "https://linkedin.com/in/maryacuna" # Add your linkedln handle
github: "https://github.com/meacuna882"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

